services:

  sig350-adapter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNAME: ofauser
        UID: ${USER_UID}
    image: ofa/sig350
    environment:
      - SIG350_IP=10.0.0.250
      - DEVICE_ALIAS=master1port4
    volumes:
      - ".:/ofa"
    expose:
      - 7878
    ports:
      - 7878:7878
    entrypoint: python3 -u sig350adapter.py
    networks:
      - factory-net

networks:
  factory-net:
    name: factory-net
    driver: overlay
    external: true
