# DHT sensor

version: '3'

services:

  dht-agent:
    image: rwuthric/mtcagent
    container_name: mtc-dht-001-agent
    environment:
      - MTC_AGENT_UUID=${MTC_AGENT_UUID}
      - ADAPTER_IP=${ADAPTER_IP}
      - ADAPTER_PORT=${ADAPTER_PORT}
    volumes:
      - "./mtconnect:/home/agent/mtconnect"
    expose:
      - 5000
    ports: 
      - "${PUBLIC_PORT}:5000"
    networks:
      - factory-net
    command: mtcagent run mtconnect/agent.cfg
    
  dht-producer:
    image: rwuthric/kafka-mtc-producer
    container_name: mtc-dht-001-producer
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - MTC_AGENT=${MTC_AGENT}
      - MTC_AGENT_UUID=${MTC_AGENT_UUID}
      - KAFKA_PRODUCER_UUID=${KAFKA_PRODUCER_UUID}
    networks:
      - factory-net
    depends_on:
      - dht-agent

networks:

    factory-net:
      name: factory-net
      driver: bridge
      external: true
