# OpenFactory configuration

# OpenFactory User
OPENFACTORY_USER: openfactory

# OpenFactory Manager Node
OPENFACTORY_MANAGER_NODE: ${MANAGER_NODE_IP}

# OpenFactory Overlay network
OPENFACTORY_NETWORK: factory-net

# OpenFactory Database
SQL_ALCHEMY_CONN: ${SQL_ALCHEMY_CONN}

# Kafka-Cluster
KAFKA_BROKER: broker:29092

# ksqlDB server
KSQLDB: http://ksqldb-server:8088

# Docker Images
MTCONNECT_AGENT_IMAGE: rwuthric/mtcagent
MTCONNECT_AGENT_CFG_FILE: ${MTCONNECT_AGENT_CFG_FILE}
MTCONNECT_PRODUCER_IMAGE: rwuthric/kafka-mtc-producer

# Colors for ofa cli
OFA_SUCCSESS: "\e[0;32m"
OFA_FAIL: "\e[0;31m"
OFA_END: "\e[0m"
