# InfluxDB server - For development only. Do not use in production

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=OpenFactory
      - DOCKER_INFLUXDB_INIT_BUCKET=ofa_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ofa_admintoken
      - DOCKER_INFLUXDB_INIT_TOKEN=ofa_developmenttoken
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - influxdb-net

networks:
  influxdb-net:
    driver: bridge

volumes:
  influxdb-data:
    driver: local
