name: Check OpenFactory Config File on Release

on:
  release:
    types: [published]

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Extract release version
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Check config for correct version
      run: |
        if grep -q "ghcr.io/demo-smart-factory-concordia-university/kafka-mtc-producer:${RELEASE_VERSION}" openfactory/config/openfactory.yml; then
          echo "✅ OpenFactory Config File contains correct version references."
        else
          echo "❌ OpenFactory Config File does not contain correct version reference ${RELEASE_VERSION}!"
          exit 1
        fi
