name: Check OpenFactory Config File on Release

on:
  release:
    types: [published]

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Extract release version
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Check openfactory-version.txt for correct version
      run: |
        if grep -q "${RELEASE_VERSION}" openfactory-version.txt; then
          echo "✅ openfactory-version.txt contains correct version references."
        else
          echo "❌ openfactory-version.txt does not contain correct version ${RELEASE_VERSION}!"
          exit 1
        fi
