name: Check OpenFactory Version on Release

on:
  release:
    types: [published]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Extract release version (strip leading 'v')
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Extract version from pyproject.toml
      run: |
        VERSION=$(grep '^version' pyproject.toml | head -n 1 | cut -d '"' -f2)
        echo "PYPROJECT_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Detected pyproject.toml version: $VERSION"

    - name: Check if pyproject.toml version matches release tag
      run: |
        if [[ "$PYPROJECT_VERSION" == "$RELEASE_VERSION" ]]; then
          echo "✅ Version in pyproject.toml matches the release tag."
        else
          echo "❌ pyproject.toml version ($PYPROJECT_VERSION) does NOT match release tag ($RELEASE_VERSION)!"
          exit 1
        fi
