name: Create InfluxDB-Connector Docker image on DockerHub

on: [workflow_dispatch]

jobs:
  push_to_registry:
    name: Create and push Docker image for InfluxDB-Connector to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./InfluxDB/connector
          file: ./InfluxDB/connector/Dockerfile
          push: true
          tags: rwuthric/inlfuxdb-connector
          build-args: |
              UNAME=${{ vars.FACTORY_USER }}
              UID=${{ vars.FACTORY_USER_UID }}
              GID=${{ vars.FACTORY_USER_GID }}
