name: Create Kafka-MTC-Producer Docker image on DockerHub

on: [workflow_dispatch]

jobs:
  push_to_registry:
    name: Create and push Docker image for Kafka-MTC-Producer to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v3
          
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./MTC2Kafka
          file: ./MTC2Kafka/Dockerfile
          push: true
          tags: rwuthric/kafka-mtc-producer
          build-args: |
              UNAME=${{ vars.FACTORY_USER }}
              UID=${{ vars.FACTORY_USER_UID }}
              GID=${{ vars.FACTORY_USER_GID }}
