name: Create Kafka-MTC-Producer Docker image on GitHub Container Registry

on: [workflow_dispatch]

jobs:
  push_to_registry:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./MTConnect/MTC2Kafka
          file: ./MTConnect/MTC2Kafka/Dockerfile
          push: true
          tags: ghcr.io/demo-smart-factory-concordia-university/kafka-mtc-producer:latest
          build-args: |
              UNAME=${{ vars.FACTORY_USER }}
              UID=${{ vars.FACTORY_USER_UID }}
              GID=${{ vars.FACTORY_USER_GID }}
