name: Lint with Flake8

on:
  workflow_dispatch:
  workflow_call:

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          python3 -m flake8 .
