name: Create MTConnect Agent Docker image on GitHub Container Registry

on: [workflow_dispatch]

env:
  CPPAGENT_VERSION: v2.5.0.4

jobs:
  push_to_registry:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out MTConnect Agent repo
        uses: actions/checkout@v4
        with:
          repository: mtconnect/cppagent
          ref: ${{ env.CPPAGENT_VERSION }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/ubuntu/Dockerfile
          push: true
          tags: ghcr.io/demo-smart-factory-concordia-university/mtcagent:${{ env.CPPAGENT_VERSION }}
          build-args: |
              UID=${{ vars.FACTORY_USER_UID }}
              GID=${{ vars.FACTORY_USER_GID }}
