name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    uses: ./.github/workflows/lint.yml

  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unittests.yml
